### ISSUE TITLE
DEFAULT PROTOCOL SELECTION

### ISSUE THREAD

**Issue by zeeshanalisyed** [Emallates/enoa-client#4]
I was configuring enoa-client with a following host.
 `host: 192.168.0.25`

Now My question is if i configure a host without specific protocol, Would enoa-client create a url for host including default protocol selected by enoa-client itself?

If yes then still I had to give the host like this `host: http://192.168.0.25` then it will work for the communication otherwise i have to manually concatenate the protocol with the host.

**Comment by nomi-ramzan** [comment]
It is not related to `enoa-client` it depends on adapter which you want to use. Enoa-client will just manage communication with server. Adapter is responsible of making Server `link/URL`.

**Comment by zeeshanalisyed** [comment]
Ok I didn't know about the default protocol selection.

URL is clear  `domain.com/api` that is related to adapter but what about default protocol if is not given for communication, because it is base of communication?

1) What if adapter didn't give the protocol information then? 
2) Will request call  be rejected by enoa-client? `OR` Will default Protocol be set by enoa-client?
